gcc -pipe -O2 -c -ansi -x c compile_to_c37.c
gcc -pipe -O2 -c -ansi -x c compile_to_c36.c
gcc -pipe -O2 -c -ansi -x c compile_to_c35.c
gcc -pipe -O2 -c -ansi -x c compile_to_c34.c
gcc -pipe -O2 -c -ansi -x c compile_to_c33.c
gcc -pipe -O2 -c -ansi -x c compile_to_c32.c
gcc -pipe -O2 -c -ansi -x c compile_to_c31.c
gcc -pipe -O2 -c -ansi -x c compile_to_c30.c
gcc -pipe -O2 -c -ansi -x c compile_to_c29.c
gcc -pipe -O2 -c -ansi -x c compile_to_c28.c
gcc -pipe -O2 -c -ansi -x c compile_to_c27.c
gcc -pipe -O2 -c -ansi -x c compile_to_c26.c
gcc -pipe -O2 -c -ansi -x c compile_to_c25.c
gcc -pipe -O2 -c -ansi -x c compile_to_c24.c
gcc -pipe -O2 -c -ansi -x c compile_to_c23.c
gcc -pipe -O2 -c -ansi -x c compile_to_c22.c
gcc -pipe -O2 -c -ansi -x c compile_to_c21.c
gcc -pipe -O2 -c -ansi -x c compile_to_c20.c
gcc -pipe -O2 -c -ansi -x c compile_to_c19.c
gcc -pipe -O2 -c -ansi -x c compile_to_c18.c
gcc -pipe -O2 -c -ansi -x c compile_to_c17.c
gcc -pipe -O2 -c -ansi -x c compile_to_c16.c
gcc -pipe -O2 -c -ansi -x c compile_to_c15.c
gcc -pipe -O2 -c -ansi -x c compile_to_c14.c
gcc -pipe -O2 -c -ansi -x c compile_to_c13.c
gcc -pipe -O2 -c -ansi -x c compile_to_c12.c
gcc -pipe -O2 -c -ansi -x c compile_to_c11.c
gcc -pipe -O2 -c -ansi -x c compile_to_c10.c
gcc -pipe -O2 -c -ansi -x c compile_to_c9.c
gcc -pipe -O2 -c -ansi -x c compile_to_c8.c
gcc -pipe -O2 -c -ansi -x c compile_to_c7.c
gcc -pipe -O2 -c -ansi -x c compile_to_c6.c
gcc -pipe -O2 -c -ansi -x c compile_to_c5.c
gcc -pipe -O2 -c -ansi -x c compile_to_c4.c
gcc -pipe -O2 -c -ansi -x c compile_to_c3.c
gcc -pipe -O2 -c -ansi -x c compile_to_c2.c
gcc -pipe -O2 -c -ansi -x c compile_to_c1.c
gcc -pipe -O2 -o compile_to_c compile_to_c[1-9].o compile_to_c[1-2][0-9].o compile_to_c3[0-7].o -x none -lm 
strip compile_to_c
